all:
  children:
    linux_apt:
      hosts:
        cymru:
          ansible_host: 100.76.202.39
          ansible_user: tavin
        faeh-inv-server:
          ansible_host: 100.75.200.8
          ansible_user: tavin
        benu:
          ansible_host: 100.116.157.54
          ansible_user: root
        nextcloud:
          ansible_host: 100.108.101.78
          ansible_user: root
        omv-moms:
          ansible_host: 100.92.162.17
          ansible_user: tavin
        watson-2:
          ansible_host: 100.112.10.10
          ansible_user: tavin
        tjd-server:
          ansible_host: 100.111.187.67
          ansible_user: tavin
