all:
  children:
    linux_apt:
      hosts:
        benu:
          ansible_host: 100.116.157.54
          ansible_user: root
        nextcloud:
          ansible_host: 100.108.101.78
          ansible_user: root
        tjd-server:
          ansible_host: 100.111.187.67
          ansible_user: tavin
        faeh-silver:
          ansible_host: 100.93.87.77
          ansible_user: tavin
        dub-silver:
          ansible_host: 100.83.147.51
          ansible_user: tavin
    linux_apk:
      hosts:
        zephyr:
          ansible_host: 100.117.193.128
          ansible_user: tavin
