all:
  children:
    linux_apt:
      hosts:
        cymru:
          ansible_host: 100.76.202.39
          ansible_user: tavin
        inventory-server:
          ansible_host: 100.75.200.8
          ansible_user: tavin
        radxa-zero:
          ansible_host: 100.86.252.52
          ansible_user: tavin
        pve-benu:
          ansible_host: 100.116.157.54
          ansible_user: root
        pve-benu-odoo:
          ansible_host: 100.91.81.60
          ansible_user: tavin
        pve-benu-mattermost:
          ansible_host: 100.74.3.127
          ansible_user: tavin
        pve-benu-etherpad:
          ansible_host: 100.71.101.76
          ansible_user: tavin
        pve-benu-ghost:
          ansible_host: 100.126.137.41
          ansible_user: tavin
        pve-benu-nextcloud:
          ansible_host: 100.108.101.78
          ansible_user: root
        pve-benu-omv-moms:
          ansible_host: 100.92.162.17
          ansible_user: tavin
        watson-2:
          ansible_host: 100.112.10.10
          ansible_user: tavin
    # linux_apk:
    #   hosts:
    #     poe:
    #       ansible_host: 100.92.136.67
    #       ansible_user: tavin
    mac_brew:
      hosts:
        mac-mini:
          ansible_host: 100.122.98.119
          ansible_user: tavin
