all:
  children:
    linux_apt:
      hosts:
        cymru:
          ansible_host: 100.76.202.39
          ansible_user: tavin
        faeh-1:
          ansible_host: 100.107.91.37
          ansible_user: tavin
        nextcloud:
          ansible_host: 100.108.101.78
          ansible_user: root
        omv-moms:
          ansible_host: 100.92.162.17
          ansible_user: tavin
        pihole-moms:
          ansible_host: 100.119.49.53
          ansible_user: tavin
        centari:
          ansible_host: 100.97.6.64
          ansible_user: tavin
        radxa-zero:
          ansible_host: 100.86.252.52
          ansible_user: tavin
        # svedka:
        #   ansible_host: 100.111.187.67
        #   ansible_user: tavin
        pve-benu:
          ansible_host: 100.116.157.54
          ansible_user: root
        pve-benu-odoo:
          ansible_host: 100.91.81.60
          ansible_user: tavin
        pve-benu-mattermost:
          ansible_host: 100.74.3.127
          ansible_user: tavin
        pve-benu-etherpad:
          ansible_host: 100.71.101.76
          ansible_user: tavin
        pve-benu-ghost:
          ansible_host: 100.126.137.41
          ansible_user: tavin
        tjd-workstation:
          ansible_host: 100.95.180.37
          ansible_user: tavin
    linux_apk:
      hosts:
        nine:
          ansible_host: 100.100.20.114
          ansible_user: tavin
    mac_brew:
      hosts:
        mac-mini:
          ansible_host: 100.122.98.119
          ansible_user: tavin
