- name: Update Linux devices using APT
  hosts: all
  gather_facts: no
  become: yes
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Fetch SSH keys from URL
      uri:
        url: "https://github.com/tavindotson.keys"
        return_content: yes
      register: fetched_keys

    - name: Add SSH keys from URL
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ item }}"
      loop: "{{ fetched_keys.content | regex_replace('\n$', '') | split('\n') }}"
      when: fetched_keys.status == 200
