- name: Update Linux devices using APT
  hosts: all
  gather_facts: no
  become: yes
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Add Jerry Public Key
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPHTaaz20YUzb4uGpzpScbsIxr4H79vbJRIANvroUu57 tjd@tavin.xyz"
