- name: Get Info
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Display CPU information
      debug:
        msg: "CPU Model: {{ ansible_processor }}"
