- name: Update Linux devices using APT
  hosts: linux_apt
  gather_facts: false
  become: true
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
      register: apt_update_result

    - name: Upgrade packages
      apt:
        upgrade: yes
        update_cache: yes
      register: apt_upgrade_result

    - name: Clean APT cache
      apt:
        autoclean: yes

    - name: Remove unused packages
      apt:
        autoremove: yes

- name: Update Linux devices using APK
  hosts: linux_apk
  gather_facts: false
  become: true
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Update APK package cache
      apk:
        update_cache: yes

    - name: Upgrade packages
      apk:
        upgrade: yes

- name: Update Mac devices using BREW
  hosts: mac_brew
  gather_facts: false
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Update Homebrew packages
      homebrew:
        update_homebrew: yes
