- name: Create Users
  hosts: linux_apt:linux_apk
  become: yes
  gather_facts: no
  vars:
    users_list:
      - tavin
  tasks:
    - name: Create users
      user:
        name: "{{ item }}"
        state: present
        shell: /bin/zsh
        createhome: true
        create_home: true
        append: yes
        generate_ssh_key: true
        update_password: on_create

      with_items: "{{ users_list }}"

    - name: Create users and add to wheel group (apk only)
      user:
        name: "{{ item }}"
        state: present
        groups: wheel
        append: yes
      with_items: "{{ users_list }}"
      when: "'linux_apk' in group_names"

    - name: Create users and add to sudo group (apt only)
      user:
        name: "{{ item }}"
        state: present
        groups: sudo
        append: yes
      with_items: "{{ users_list }}"
      when: "'linux_apt' in group_names"

    - name: Add Jerry Public Key
      ansible.posix.authorized_key:
        user: "{{ item }}"
        state: present
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPHTaaz20YUzb4uGpzpScbsIxr4H79vbJRIANvroUu57 tjd@tavin.xyz"
      with_items: "{{ users_list }}"

    - name: Create sudoers file for passwordless sudo (tavin only)
      copy:
        dest: /etc/sudoers.d/tavin-user
        content: "tavin ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
      when: "'linux_apt' in group_names"

    - name: Add .hushlogin to users' home folders
      copy:
        dest: "/home/{{ item }}/.hushlogin"
        content: ""
      with_items: "{{ users_list }}"
      ignore_errors: yes
